---
name: futago
description: Google gemini chat for vim.
---

=pod

=head1 futago.vim

Google gemini chat for Vim / Neovim.

![futago](https://github.com/yukimemi/futago.vim/assets/6442108/2a9f13c1-a66f-4170-aba3-e44a417ef5f7)

=head1 Features X<futago-features>

This plugin is a Google gemini chat for Vim / Neovim.

=head1 Installation X<futago-installation>

If you use L<folke/lazy.nvim|https://github.com/folke/lazy.nvim>.

=begin lua

{
  "yukimemi/futago.vim",
  lazy = false,
  dependencies = {
    "vim-denops/denops.vim",
  },
}

=end lua

If you use L<yukimemi/dvpm|https://github.com/yukimemi/dvpm>.

=begin typescript

dvpm.add({ url: "yukimemi/futago.vim" });

=end typescript

=head1 Requirements X<futago-requirements>

=item [Deno - A modern runtime for JavaScript and TypeScript](https://deno.land/)

=item [vim-denops/denops.vim: 🐜 An ecosystem of Vim/Neovim which allows developers to write cross-platform plugins in Deno](https://github.com/vim-denops/denops.vim)

=item Environment: `GEMINI_API_KEY`

[Get API key](https://ai.google.dev/)

=head1 Usage X<futago-usage>

=head1 Commands X<futago-commands>

C<:FutagoStart [opener]>                                          X<:FutagoStart>

Start Futago chat.
Enter the prompt, save buffer, and the chat will be sent.

[opener]: Optional. Default is "tabnew".

Options are "split", "vsplit", "tabnew", "edit", "new", "vnew".

C<:FutagoHistory>                                               X<:FutagoHistory>

Show list of chat history with quickfix.
If you open a past chat file, you can start chatting based on the automatically saved history.

=head1 Config X<futago-config>

No settings are required. However, the following settings can be made if necessary.

C<g:futago_debug>                                               X<g:futago_debug>
Enable debug messages.
default is v:false

C<g:futago_chat_path>                                       X<g:futago_chat_path>
Path to save chat files.
default is `xdg.cache()/futago/chat`

https://deno.land/x/xdg/src/mod.deno.ts

If you open a past chat file saved in g:futago_chat_path, you can start chatting based on the automatically saved chat history.

C<g:futago_log_file>                                         X<g:futago_log_file>
Path to save log files.
default is `xdg.cache()/futago/log`

https://deno.land/x/xdg/src/mod.deno.ts

=head1 Example X<futago-example>

=begin vim

let g:futago_debug = v:true
let g:futago_chat_path = '~/.cache/vim/futago/chat'
let g:futago_log_file = '~/.cache/vim/futago/log/futago.log'

=end vim

=head1 License X<futago-license>

Licensed under MIT License.

Copyright (c) 2023 yukimemi

=cut
